CREATE TABLE USERS (
  ID INTEGER NOT NULL,
  NAME VARCHAR(25),
  PASS VARCHAR(25),
  PRIMARY KEY (ID)
);

INSERT INTO USERS VALUES (1, 'ryan', 'nayr');
INSERT INTO USERS VALUES (2, 'jerric', 'cirrej');
INSERT INTO USERS VALUES (3, 'steve', 'evets');
